[package]
name = "async_once_jwt_simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# jwt-simple is the culprit
# jwt-simple = "0.11"
lazy_static = "1.4"
async_once = "0.2.6"
